"""Generate a per-hull docker-compose from the base (USS Theseus) one, with a port offset
and a hull-prefixed project + container names — so sister hulls DDG-119/120 run their OWN
6 subsystem containers alongside the flagship, every hull a self-contained city.

  python3 gen_hull.py DDG-119 10     # -> docker-compose.ddg-119.yml (ports 5455x)
  python3 gen_hull.py DDG-120 20     # -> docker-compose.ddg-120.yml (ports 5456x)

All hulls share the same registered <key>_deploy models + configs + features (sister ships
run the identical stack); ship_feed.py feeds each hull's ports with a per-hull phase so they
don't move in lockstep. Bring one up with:
  docker compose -p <hull-slug> -f docker-compose.<hull-slug>.yml up -d
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BASE_PORTS = (54541, 54542, 54543, 54544, 54545, 54546)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_hull.py <HULL e.g. DDG-119> <PORT_OFFSET e.g. 10>"); return 2
    hull, offset = sys.argv[1], int(sys.argv[2])
    slug = hull.lower()
    s = (HERE / "docker-compose.yml").read_text()
    s = s.replace("name: theseus-ddg118", f"name: theseus-{slug}")
    s = s.replace("container_name: theseus-", f"container_name: theseus-{slug}-")
    for p in BASE_PORTS:
        s = s.replace(f'"{p}:54321"', f'"{p + offset}:54321"')
    s = ("# AUTO-GENERATED by gen_hull.py — sister hull of USS Theseus (DDG-118).\n"
         f"# Hull {hull}: subsystem ports offset by +{offset} ({BASE_PORTS[0] + offset}-"
         f"{BASE_PORTS[-1] + offset}). Same models/configs/features as the flagship.\n" + s)
    out = HERE / f"docker-compose.{slug}.yml"
    out.write_text(s)
    print(f"  wrote {out.name}  (ports {BASE_PORTS[0] + offset}-{BASE_PORTS[-1] + offset}, project theseus-{slug})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
