apiVersion: v1
kind: Pod
metadata:
  name: bad-hostpath
  namespace: theseus
  labels:
    app.kubernetes.io/part-of: theseus
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
  volumes:
    - name: hostescape
      hostPath: { path: /etc }
  containers:
    - name: escaper
      image: theseus-edge:0.1.0
      command: ["sleep","3600"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities: { drop: ["ALL"] }
