apiVersion: v1
kind: Pod
metadata:
  name: bad-privileged
  namespace: theseus
  labels:
    app.kubernetes.io/part-of: theseus
spec:
  containers:
    - name: evil
      image: theseus-edge:0.1.0
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
        runAsUser: 0
