apiVersion: v1
kind: Pod
metadata:
  name: bad-root
  namespace: theseus
  labels:
    app.kubernetes.io/part-of: theseus
spec:
  containers:
    - name: rooty
      image: theseus-edge:0.1.0
      command: ["sleep", "3600"]
